title: Your Site Title
description: >- # this means to ignore newlines until "baseurl:"
  Your site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io/your-repo-name" # the base hostname & protocol for your site
